---
- name: Install pyenv
  ansible.builtin.shell:
    cmd: curl -fsSL https://pyenv.run | bash
    creates: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    extra_args: --user --break-system-packages
    state: present

- name: Install pipx packages
  community.general.pipx:
    name: "{{ item }}"
    state: install
  loop: "{{ pipx_packages }}"
