- name: env - setup
  hosts: local

  roles:
    - role: apt
      become: true

    - role: git

    - role: zsh

    - role: dotfiles

    - role: neovim
      become: true

    - role: go
    - role: node
    - role: python
    - role: java

    - role: opencode
